### ISSUE TITLE
Yrewrite Multidomain Support

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/icecoder#13]
Habe in einem Multidomain-Setup das Problem, dass die URL domain.com/icecoder einen Redirect auf die 404-Seite bringt. 
Evtl spielt auch eine Rolle, dass YCom installiert und aktiviert ist, das die Userrechte für icecoder abfragen möchte und dann den Redirect initiiert.

**Comment by skerbis** [comment]
Welche Version vom AddOn?

**Comment by cukabeka** [comment]
Die aktuelle Version direkt hier aus Github via URL install gezogen.

**Comment by skerbis** [comment]
in REDAXO 5.7 ???

**Comment by skerbis** [comment]
Ich kann es in einer Multidomain-Umgebung ohne ycom nicht reproduzieren unter 5.7

**Comment by staabm** [comment]
ich vermute dass ggf. durch rewrite rules der interne request zur authentifizierung nicht funktioniert.

**Comment by skerbis** [comment]
unterscheidet sich die Backend-Url von der Frontend-Url? (evtl. aufgrund eines beim Hoster eingestellten Autorewrites)

**Comment by cukabeka** [comment]
Nee, R5.6.4 - ich schau mal, ob es nach dem update auch noch so ist.

**Comment by staabm** [comment]
Versuch ma domain.com/icecoder/index.php

**Comment by cukabeka** [comment]
Spannend - mir fällt gerade auf, dass alles auf 
bla.de/icecoder/settings.php
weiterleitet

Also, "alles" =
bla.de/icecoder/index.php
bla.de/icecoder/
bla.de/icecoder

**Comment by staabm** [comment]
Welche version des addon nutzt du mit welcher redaxo version?

**Comment by cukabeka** [comment]
1.0.0-beta1 (also vorgestern direkt via "Install ZIP from URL" Addon im Installer von Github geholt) mit R5.6.4

**Comment by staabm** [comment]
Diese addon version erfordert redaxo 5.7-beta

**Comment by skerbis** [comment]
dann ist klar warum da ein 404 kommt - close

**Comment by cukabeka** [comment]
Okay, bin gespannt auf den Test in R5.7, wenn das raus ist.

Habe mir für meine R5.6 Umgebung gerade allerdings nochmal einen alten Blob gezogen und das hier in R5.6 installiert: 
https://github.com/FriendsOfREDAXO/icecoder/archive/a08502bc556f247da8a75da943d5731b5be8b6bf.zip
In einer non-Multidomain-Installation funktioniert es, in der Multidomain-Umgebung gibt's wieder nen 404. Bin also nicht sicher, ob das in 5.7 gelöst sein wird. Daher vorerst nur als Reference.
