### ISSUE TITLE
Installer-Version anbieten

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/icecoder#14]
kwT

**Comment by skerbis** [comment]
@alexplusde Ja, wenn REDAXO 5.7 released ist. Eine Verwendung unter 5.7 ist nicht möglich.

**Comment by AWqxKAWERbXo** [comment]
Ah, deswegen...

**Comment by skerbis** [comment]
Für das sso ist 5.7. erforderlich. Coole Sache dank @staabm

**Comment by AWqxKAWERbXo** [comment]
da es auch in der README.md steht, mein Fehler.

**Comment by staabm** [comment]
@gharlan man kann vermutlich das addon schon in den installer legen, oder?
(es wird sich dann nicht installieren lassen)

**Comment by skerbis** [comment]
Ich möchte ungerne für Verwirrung sorgen. Oder zeigt er Installer nur die AddOns an, die zur aktuell installierten Version passen?
