### ISSUE TITLE
Curl error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/icecoder#15]
Meldung: auf https://abc.de/icecoder/

>   Curl error 60: SSL certificate problem: unable to get local issuer certificate

REDAXO 5.7.0-beta1
MAMP + durch MAMP selbst erstelltest SSL Zertifikat

**Comment by staabm** [comment]
Selbst signierte zertifikate sind eine sicherheitslücke, daher nicht per default erlaubt.

https://github.com/FriendsOfREDAXO/icecoder/blob/7a34cbaefdb186ba612a78d9a337af4f709532dc/config___settings.php#L19-L21

Hier aktivierbar, danach addon re-installieren

**Comment by olien** [comment]
Ah. Ok. Danke für die Erklärung!
