### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/icecoder#16]
Internal Server Error
File "/home/.../html/www/icecoder/index.php" is writeable by group
suPHP 0.7.2

<details>
<summary>System report (REDAXO 5.7.1, PHP 7.1.16)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.7.1      |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.1.16     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.6.35-log             |
| Character set | utf8 (utf8_general_ci) |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/73.0.3683.103 |
|      Protocol | HTTP/1.1             |
|         HTTPS | yes                  |

| Packages                |            |
| ----------------------: | :--------- |
|            accessdenied | 1.0.5      |
|                 adminer | 1.5.0      |
|                  backup | 2.3.0      |
|                be_style | 2.7.1      |
|     be_style/customizer | 2.7.0      |
|         be_style/redaxo | 2.7.0      |
|                 bloecks | 1.3.15     |
|        bloecks/cutncopy | 1.3.12     |
|          bloecks/status | 1.3.12     |
|            cache_warmup | 3.6.0      |
|                 cronjob | 2.4.1      |
|               developer | 3.8.0      |
|                   dsgvo | 0.9beta5   |
|         global_settings | 2.1.0      |
|                   hello | 0.4.4-dev  |
|                icecoder | 1.0.0      |
|                 install | 2.5.0      |
|             maintenance | 2.0.0      |
|                markitup | 3.2.0      |
|  markitup/documentation | 1.0.1      |
|                  mblock | 2.2.3      |
|           media_manager | 2.6.0      |
|               mediapool | 2.5.0      |
|                metainfo | 2.4.0      |
|                   mform | 5.2.4      |
|              mform/docs | 1.0        |
|                  minify | 2.1.0      |
|               phpmailer | 2.5.1      |
|              pixelfirma | 1.2.6      |
|     pixelfirma/px_admin | 1.1        |
|       pixelfirma/px_lib | 1.2        |
|                 project | dev        |
|        quick_navigation | 3.5.8      |
|               search_it | 6.6.5      |
| search_it/documentation | 6.6.5      |
|                    sked | 1.7.1      |
|                sked_ics | 0.1        |
|               structure | 2.7.0      |
|       structure/content | 2.7.0      |
|                   theme | 1.1.1      |
|                uploader | 2.0.4      |
|                     url | 1.0.1      |
|                   users | 2.5.2      |
|                    ycom | 3.0-beta4  |
|               ycom/auth | 3.0-beta4  |
|               ycom/docs | 3.0-beta4  |
|              ycom/group | 3.0-beta4  |
|                   yform | 3.0        |
|              yform/docs | 3.0        |
|             yform/email | 3.0        |
|           yform/manager | 3.0        |
|         yform_usability | 1.4        |
|                yrewrite | 2.5        |

</details>

**Comment by skerbis** [comment]
Lokale mamp Installation?

**Comment by skerbis** [comment]
kann ich nicht reproduzieren ... wieder öffnen wenn mehr bekannt

**Comment by AWqxKAWERbXo** [comment]
War nich lokal, ich mache gerade einen Bogen um den Icecoder deswegen.

**Comment by staabm** [comment]
Ob lokal oder nicht. Die Fehlermeldung sagt es ist ein rechteproblem im filesystem.

Wann taucht der error auf?

**Comment by skerbis** [comment]
Dieses Issue scheint ebenfalls ein Dateirechteproblem zu benennen: https://github.com/FriendsOfREDAXO/icecoder/issues/19

**Comment by skerbis** [comment]
suPHP ??? Huch, das habe ich schon ewig nicht mehr gesehen
