### ISSUE TITLE
Nach Installation Passwort gesetzt. Anschließend: no datano data

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/icecoder#19]
erhalte eine weiße Seite, die schreibt `no datano data`.

icecoder aktuelle Version aus dem Installer.

**Comment by staabm** [comment]
ist das ein "Artefakt" das nur bei installation auftritt oder kannst du aufgrund des problems überhaupt nicht mit dem addon/editor arbeiten?

**Comment by AWqxKAWERbXo** [comment]
Ich kann damit nicht arbeiten.

**Comment by skerbis** [comment]
Was für ein Passwort hast du gesetzt? Du brauchst kein Passwort

**Comment by AWqxKAWERbXo** [comment]
Es kam eine Oberfläche vom Icecoder, in der ich ein Passwort setzen sollte.

**Comment by skerbis** [comment]
dann war's nicht die aktuelle Version. Am besten mal alles entfernen und neu installieren. Auch den Ordner /icecoder im Webroot. Ein anderer Grund könnten Dateirechte sein. 
https://github.com/icecoder/ICEcoder/issues/718 oder fehlendes  fopen

**Comment by AWqxKAWERbXo** [comment]
ok, ich werde es nochmal versuchen...
