### ISSUE TITLE
Upgrade auf 8.1

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/icecoder#20]
Leider sehe ich hier keine Möglichkeit das Login wie in 6 und 7 zu realisieren.

**Comment by staabm** [comment]
ich vermute in diesem zuge könnte/sollten wir die integration auch auf composer umstellen:
https://packagist.org/packages/icecoder/icecoder

**Comment by staabm** [comment]
> Leider sehe ich hier keine Möglichkeit das Login wie in 6 und 7 zu realisieren.

d.h. was konnte icecode 5 was jetzt in 6/7 nicht mehr geht?

**Comment by staabm** [comment]
wg. unserer konfig hier im addon hab ich mal nen issue aufgemacht:
https://github.com/icecoder/ICEcoder/issues/953

**Comment by skerbis** [comment]
Icecoder 8 ist schön schnell und stürzt nicht mehr ab. 
Ja es ist serialisiert und im Quellcode kann ich auch nicht entdecken ob eine allgemeine config hinterlegt werden kann.
Ich sehe nur dass jetzt nur noch configs erzeugt werden können, die den Namen der Domain haben.
Es gibt schon ein issue das ich gestern angegangen bin. Klar ist nicht wo diese Settings erstellt werden müssen. 
Durch Manipulation der settings.php habe ich eine lauffähige Version hinbekommen - aber das ist natürlich nicht updatesicher.

ein issue hatte ich schon mal angelegt

https://github.com/icecoder/ICEcoder/issues/910
Einen Tipp für die Erstellung gibts auch. 
Das vergaß ich gestern im issue zu ergänzen

**Comment by skerbis** [comment]
Zu https://github.com/icecoder/ICEcoder/issues/953 ich bin zwar jetzt etwas schlauer, aber so ganz ist mir nicht klar wann und wo wir die config bei der Installation erstellen können

**Comment by cukabeka** [comment]
Hi @skerbis danke dass Du Dir das schon angeschaut hast. Anscheinend ist es ja immer noch unklar, wie das geht. Könntest aber vielleicht mal kurz beschreiben, wie Du das mit der Manipulation der settings.php hinbekommen hast? 
Dann könnte ich das wenigstens schon mal manuell nachbauen.

**Comment by skerbis** [comment]
Hatte keine Zeit mich damit zu beschäftigen. Leider

**Comment by skerbis** [comment]
@staabm ich habe es noch mal in Ruhe umgesetzt. Kannst du noch mal schauen ob sich was optimieren lässt? 
(Sicherheit, Installationsvorgang und so?)
