### ISSUE TITLE
Icecoder unter domain.de/icecoder erreichbar, auch wenn inaktiv

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/icecoder#22]
**Description / Beschreibung**
Ich denke man sollte Icecoder nicht aufrufen können, wenn das Addon deaktiviert ist. 
Aktuell kann ich es deaktivieren und über domain.de/icecoder aufrufen. 

**Affected versions / Verwendete Versionen**
3.0.1

**Comment by skerbis** [comment]
Sicher ? https://klxm.de/icecoder/

**Comment by skerbis** [comment]
@eaCe , ja aber nur wenn du in Redaxo angemeldet bist. Mal schauen ob noch irgendwie ne Prüfung einbauen kann.

**Comment by eaCe** [comment]
@skerbis ich wüsste aktuell auch nicht wie man das machen könnte.
Es wird kein Code aus dem Addon ausgeführt, wenn dieses deaktiviert ist.
Einen EP, wenn das Addon deaktiviert wird, gibt es auch nicht um dann eine .htaccess oder index.php oder sowas zu setzen.

**Comment by staabm** [comment]
ich denke bei deaktivierung des addons könnte man die `rex_path::frontend('icecoder/data/config-global.php')` verändern, sodass der icecoder nicht mehr funktioniert

https://github.com/FriendsOfREDAXO/icecoder/blob/31f117ac9fa8a8532b6d195819e4f174ed63a891/install.php#L19

**Comment by eaCe** [comment]
@staabm auch dann wüsste ich nicht, wie man feststellen könnte, dass das Addon deaktiviert wurde.

**Comment by staabm** [comment]
hmm stimmt, wenn deaktiviert wird, kommt das addOn selbst nicht mehr zum zuge.

dann bleibt die umgekehrte Idee: in der `rex_path::frontend('icecoder/data/config-global.php')` den redaxo core booten und abfragen ob das addon aktiv ist

**Comment by eaCe** [comment]
Alternativ kann auch 404 statt einer Nachricht ausgegeben werden. Fänd ich besser statt `Login nur als REDAXO Admin erlaubt!`
Können aber auch gerne schließen. Wenn ich das Addon mal live nutze, deinstalliere ich es danach wieder.

**Comment by skerbis** [comment]
@eaCe PR welcome 😀
