### ISSUE TITLE
https is required for this addon to work properly

### ISSUE THREAD

**Issue by Koala** [FriendsOfREDAXO/icecoder#24]
Installation schlägt fehl weil:

> AddOn icecoder konnte aus folgendem Grund nicht installiert werden:
> https is required for this addon to work properly

Das https zwingend benötigt wird, sollte in  der Beschreibung erwähnt werden.

**Comment by staabm** [comment]
PR welcome

**Comment by aeberhard** [comment]
Frage: Kann man sowas eigentlich in der package.yml notieren?
```
requires:
  https
```

**Comment by staabm** [comment]
> Frage: Kann man sowas eigentlich in der package.yml notieren?

bisher nicht. requires funktioniert bisher nur für php extensions und andere addons

**Comment by skerbis** [comment]
Ich denke, das hat sich von selbst erledigt: 

https://github.com/icecoder/ICEcoder

<img width="792" alt="Bildschirmfoto 2024-01-18 um 15 07 31" src="https://github.com/FriendsOfREDAXO/icecoder/assets/791247/1232cf8a-88c4-415e-b6c1-0bcbab3b2d76">
