### ISSUE TITLE
Auto-Login?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/icecoder#4]

**Comment by skerbis** [comment]
Muss nicht sein. Man braucht das IDE doch eher um schnell mal Korrekturen durchzuführen.  Das einrichten des Passworts ist hier sehr unkompliziert gestaltet und evtl gibt es andere Admins die darauf kein Zugriff haben sollen.

**Comment by olien** [comment]
Das Problem ist, dass wenn du das AddOn installierst und dir kein ice Passwort gibst es theoretisch jeder mähen könnte...

**Comment by olien** [comment]
Mähen = machen

**Comment by skerbis** [comment]
Stimmt

**Comment by staabm** [comment]
Ich schau mir das bei Gelegenheit mal an

**Comment by staabm** [comment]
Dazu muss ich im core Voraussetzungen schaffen und dann wird das addon nur mit R5.7 und neuer funktionieren.. ist das ok?

https://github.com/redaxo/redaxo/issues/2028

Ggf würde es sich anbieten noch ein release des addons zu machen bevor R5.7 pflicht wird um auto-login dann zu unterstützen

**Comment by olien** [comment]
Das wäre super!
Ich kümmere mich später auf jedenfalls auch um die README!
