### ISSUE TITLE
vendor files als zip ausliefern

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/icecoder#8]
... und bei installation des addons entpacken

-> upload des addons wird beschleunigt (weil nicht so viele einzelne dateien)

**Comment by skerbis** [comment]
Der Installer liefert das AddOn doch komprimiert? Welchen Vorteil siehst du noch?

**Comment by staabm** [comment]
Wenn man eine dev umgebung hat und diese dann auf einen server hochlädt

**Comment by skerbis** [comment]
Warum Close?

**Comment by staabm** [comment]
wenn man nur mit dem installer arbeitet, hast du recht und dann passt das auch so.

**Comment by skerbis** [comment]
Ne Alternative das AddOn gesamt klein zu halten wäre wenn das Release aus GitHub gezogen wird. Dann würden die Dateien nicht doppelt vorliegen? Habe das mal mit REDAXO gemacht: https://friendsofredaxo.github.io/tricks/diverses/redaxo_loader

**Comment by staabm** [comment]
für redaxo macht dieser "loader" so definitiv sinn und ich finde es sollte vllt sogar die standard installation auf diesem weg gemacht werden.

allerdings fehlen mir da ein paar sicherheitsmerkmale.

für ein addon selbst, macht das aber in meinen augen keinen sinn. da gibts ja den installer.
